package wireless

// This file contains components from github.com/brlbil/wpaclient
//
// Copyright (c) 2017 Birol Bilgin
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// nd/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// UT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

const (
	CmdStatus               = "STATUS"
	CmdIfname               = "IFNAME"
	CmdPing                 = "PING"
	CmdRelog                = "RELOG"
	CmdNote                 = "NOTE"
	CmdMib                  = "MIB"
	CmdHelp                 = "HELP"
	CmdInterface            = "INTERFACE"
	CmdLevel                = "LEVEL"
	CmdLicense              = "LICENSE"
	CmdQuit                 = "QUIT"
	CmdSet                  = "SET"
	CmdDump                 = "DUMP"
	CmdGet                  = "GET"
	CmdDriverFlags          = "DRIVER_FLAGS"
	CmdLogon                = "LOGON"
	CmdLogoff               = "LOGOFF"
	CmdPmksa                = "PMKSA"
	CmdPmksaFlush           = "PMKSA_FLUSH"
	CmdReassociate          = "REASSOCIATE"
	CmdReattach             = "REATTACH"
	CmdPreauthenticate      = "PREAUTHENTICATE"
	CmdIdentity             = "IDENTITY"
	CmdPassword             = "PASSWORD"
	CmdNewPassword          = "NEW_PASSWORD"
	CmdPin                  = "PIN"
	CmdOtp                  = "OTP"
	CmdPassphrase           = "PASSPHRASE"
	CmdSim                  = "SIM"
	CmdBssid                = "BSSID"
	CmdBlacklist            = "BLACKLIST"
	CmdLogLevel             = "LOG_LEVEL"
	CmdListNetworks         = "LIST_NETWORKS"
	CmdSelectNetwork        = "SELECT_NETWORK"
	CmdEnableNetwork        = "ENABLE_NETWORK"
	CmdDisableNetwork       = "DISABLE_NETWORK"
	CmdAddNetwork           = "ADD_NETWORK"
	CmdRemoveNetwork        = "REMOVE_NETWORK"
	CmdSetNetwork           = "SET_NETWORK"
	CmdGetNetwork           = "GET_NETWORK"
	CmdDupNetwork           = "DUP_NETWORK"
	CmdListCreds            = "LIST_CREDS"
	CmdAddCred              = "ADD_CRED"
	CmdRemoveCred           = "REMOVE_CRED"
	CmdSetCred              = "SET_CRED"
	CmdGetCred              = "GET_CRED"
	CmdSaveConfig           = "SAVE_CONFIG"
	CmdDisconnect           = "DISCONNECT"
	CmdReconnect            = "RECONNECT"
	CmdScan                 = "SCAN"
	CmdScanResults          = "SCAN_RESULTS"
	CmdAbortScan            = "ABORT_SCAN"
	CmdBss                  = "BSS"
	CmdGetCapability        = "GET_CAPABILITY"
	CmdReconfigure          = "RECONFIGURE"
	CmdTerminate            = "TERMINATE"
	CmdInterfaceAdd         = "InterfaceAdd"
	CmdInterfaceRemove      = "INTERFACE_REMOVE"
	CmdInterfaceList        = "INTERFACE_LIST"
	CmdApScan               = "AP_SCAN"
	CmdScanInterval         = "SCAN_INTERVAL"
	CmdBssExpireAge         = "BSS_EXPIRE_AGE"
	CmdBssExpireCount       = "BSS_EXPIRE_COUNT"
	CmdBssFlush             = "BSS_FLUSH"
	CmdStkstart             = "STKSTART"
	CmdFtDs                 = "FT_DS"
	CmdWpsPbc               = "WPS_PBC"
	CmdWpsPin               = "WPS_PIN"
	CmdWpsCheckPin          = "WPS_CHECK_PIN"
	CmdWpsReg               = "WPS_REG"
	CmdWpsApPin             = "WPS_AP_PIN"
	CmdWpsErStart           = "WPS_ER_START"
	CmdWpsErStop            = "WPS_ER_STOP"
	CmdWpsErPin             = "WPS_ER_PIN"
	CmdWpsErPbc             = "WPS_ER_PBC"
	CmdWpsErLearn           = "WPS_ER_LEARN"
	CmdWpsErSetConfig       = "WPS_ER_SET_CONFIG"
	CmdWpsErConfig          = "WPS_ER_CONFIG"
	CmdIbssRsn              = "IBSS_RSN"
	CmdSta                  = "STA"
	CmdAllSta               = "ALL_STA"
	CmdDeauthenticate       = "DEAUTHENTICATE"
	CmdDisassociate         = "DISASSOCIATE"
	CmdChanSwitch           = "CHAN_SWITCH"
	CmdSuspend              = "SUSPEND"
	CmdResume               = "RESUME"
	CmdRoam                 = "ROAM"
	CmdP2pFind              = "P2P_FIND"
	CmdP2pStopFind          = "P2P_STOP_FIND"
	CmdP2pAspProvision      = "P2P_ASP_PROVISION"
	CmdP2pAspProvisionResp  = "P2P_ASP_PROVISION_RESP"
	CmdP2pConnect           = "P2P_CONNECT"
	CmdP2pListen            = "P2P_LISTEN"
	CmdP2pGroupRemove       = "P2P_GROUP_REMOVE"
	CmdP2pGroupAdd          = "P2P_GROUP_ADD"
	CmdP2pGroupMember       = "P2P_GROUP_MEMBER"
	CmdP2pProvDisc          = "P2P_PROV_DISC"
	CmdP2pGetPassphrase     = "P2P_GET_PASSPHRASE"
	CmdP2pServDiscReq       = "P2P_SERV_DISC_REQ"
	CmdP2pServDiscCancelReq = "P2P_SERV_DISC_CANCEL_REQ"
	CmdP2pServDiscResp      = "P2P_SERV_DISC_RESP"
	CmdP2pServiceUpdate     = "P2P_SERVICE_UPDATE"
	CmdP2pServDiscExternal  = "P2P_SERV_DISC_EXTERNAL"
	CmdP2pServiceFlush      = "P2P_SERVICE_FLUSH"
	CmdP2pServiceAdd        = "P2P_SERVICE_ADD"
	CmdP2pServiceRep        = "P2P_SERVICE_REP"
	CmdP2pServiceDel        = "P2P_SERVICE_DEL"
	CmdP2pReject            = "P2P_REJECT"
	CmdP2pInvite            = "P2P_INVITE"
	CmdP2pPeers             = "P2P_PEERS"
	CmdP2pPeer              = "P2P_PEER"
	CmdP2pSet               = "P2P_SET"
	CmdP2pFlush             = "P2P_FLUSH"
	CmdP2pCancel            = "P2P_CANCEL"
	CmdP2pUnauthorize       = "P2P_UNAUTHORIZE"
	CmdP2pPresenceReq       = "P2P_PRESENCE_REQ"
	CmdP2pExtListen         = "P2P_EXT_LISTEN"
	CmdP2pRemoveClient      = "P2P_REMOVE_CLIENT"
	CmdVendorElemAdd        = "VENDOR_ELEM_ADD"
	CmdVendorElemGet        = "VENDOR_ELEM_GET"
	CmdVendorElemRemove     = "VENDOR_ELEM_REMOVE"
	CmdStaAutoconnect       = "STA_AUTOCONNECT"
	CmdTdlsDiscover         = "TDLS_DISCOVER"
	CmdTdlsSetup            = "TDLS_SETUP"
	CmdTdlsTeardown         = "TDLS_TEARDOWN"
	CmdTdlsLinkStatus       = "TDLS_LINK_STATUS"
	CmdWmmAcAddts           = "WMM_AC_ADDTS"
	CmdWmmAcDelts           = "WMM_AC_DELTS"
	CmdWmmAcStatus          = "WMM_AC_STATUS"
	CmdTdlsChanSwitch       = "TDLS_CHAN_SWITCH"
	CmdTdlsCancelChanSwitch = "TDLS_CANCEL_CHAN_SWITCH"
	CmdSignalPoll           = "SIGNAL_POLL"
	CmdSignalMonitor        = "SIGNAL_MONITOR"
	CmdPktcntPoll           = "PKTCNT_POLL"
	CmdReauthenticate       = "REAUTHENTICATE"
	CmdRaw                  = "RAW"
	CmdFlush                = "FLUSH"
	CmdRadioWork            = "RADIO_WORK"
	CmdVendor               = "VENDOR"
	CmdNeighborRepRequest   = "NEIGHBOR_REP_REQUEST"
	CmdErpFlush             = "ERP_FLUSH"
	CmdMacRandScan          = "MAC_RAND_SCAN"
	CmdGetPrefFreqList      = "GET_PREF_FREQ_LIST"
	CmdP2pLoStart           = "P2P_LO_START"
	CmdP2pLoStop            = "P2P_LO_STOP"
)
